var timeoutIcon,timeoutSuccessClass;const messages={en:{copy:'Copy',copy_to_clipboard:'Copy to clipboard',copy_success:'Copied!',copy_failure:'Failed to copy'},es:{copy:'Copiar',copy_to_clipboard:'Copiar al portapapeles',copy_success:'¡Copiado!',copy_failure:'Error al copiar'},de:{copy:'Kopieren',copy_to_clipboard:'In die Zwischenablage kopieren',copy_success:'Kopiert!',copy_failure:'Fehler beim Kopieren'},fr:{copy:'Copier',copy_to_clipboard:'Copier dans le presse-papier',copy_success:'Copié !',copy_failure:'Échec de la copie'},ru:{copy:'Скопировать',copy_to_clipboard:'Скопировать в буфер',copy_success:'Скопировано!',copy_failure:'Не удалось скопировать'},'zh-CN':{copy:'复制',copy_to_clipboard:'复制到剪贴板',copy_success:'复制成功!',copy_failure:'复制失败'},it:{copy:'Copiare',copy_to_clipboard:'Copiato negli appunti',copy_success:'Copiato!',copy_failure:'Errore durante la copia'}};let locale='en';document.documentElement.lang!==void 0&&messages[document.documentElement.lang]!==void 0&&(locale=document.documentElement.lang);let doc_url_root=DOCUMENTATION_OPTIONS.URL_ROOT;doc_url_root=='#'&&(doc_url_root='');let iconCheck=`<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-check" width="44" height="44" viewBox="0 0 24 24" stroke-width="2" stroke="#22863a" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <title>${messages[locale].copy_success}</title>
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M5 12l5 5l10 -10" />
</svg>`,iconCopy=``;iconCopy||(iconCopy=`<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-copy" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <title>${messages[locale].copy_to_clipboard}</title>
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <rect x="8" y="8" width="12" height="12" rx="2" />
  <path d="M16 8v-2a2 2 0 0 0 -2 -2h-8a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h2" />
</svg>`);const runWhenDOMLoaded=a=>{document.readyState!='loading'?a():document.addEventListener?document.addEventListener('DOMContentLoaded',a):document.attachEvent('onreadystatechange',function(){document.readyState=='complete'&&a()})},codeCellId=a=>`codecell${a}`,clearSelection=()=>{window.getSelection?window.getSelection().removeAllRanges():document.selection&&document.selection.empty()};timeoutIcon=2e3,timeoutSuccessClass=1500;const temporarilyChangeTooltip=(a,b,c)=>{a.setAttribute('data-tooltip',c),a.classList.add('success'),setTimeout(()=>a.classList.remove('success'),timeoutSuccessClass),setTimeout(()=>a.setAttribute('data-tooltip',b),timeoutIcon)},temporarilyChangeIcon=a=>{a.innerHTML=iconCheck,setTimeout(()=>{a.innerHTML=iconCopy},timeoutIcon)},addCopyButtonToCodeCells=()=>{if(window.ClipboardJS===void 0){setTimeout(addCopyButtonToCodeCells,250);return}const g='div.highlight pre',b=document.querySelectorAll(g);b.forEach((a,c)=>{const b=codeCellId(c);a.setAttribute('id',b);const d=a=>`<button class="copybtn o-tooltip--left" data-tooltip="${messages[locale].copy}" data-clipboard-target="#${a}">
      ${iconCopy}
    </button>`;a.insertAdjacentHTML('afterend',d(b))});function c(a){return a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}function d(c,a){const b=c.cloneNode(!0);return a&&b.querySelectorAll(a).forEach(a=>a.remove()),b.innerText}function e(a,k,o=!1,r=!0,q=!0,p=!0,i="",j=""){var m=!!i,n=!!j,d,e,g,h,f;o?d=new RegExp('^('+k+')(.*)'):d=new RegExp('^('+c(k)+')(.*)');const b=[];g=!1,h=!1,f=!1;const l=[];for(const c of a.split('\n'))e=c.match(d),e||h||f?(g=d.test(c),l.push(g),q&&g?b.push(e[2]):b.push(c),h=c.endsWith(i)&m,c.includes(j)&n&&(f=!f)):r?p&&c.trim()===''&&b.push(c):b.push(c);return l.some(a=>a===!0)&&(a=b.join('\n')),a.endsWith("\n")&&(a=a.slice(0,-1)),a}var f=a=>{var b=document.querySelector(a.attributes['data-clipboard-target'].value);let c='.linenos',f=d(b,c);return e(f,'',!1,!0,!0,!0,'','')};const a=new ClipboardJS('.copybtn',{text:f});a.on('success',a=>{clearSelection(),temporarilyChangeTooltip(a.trigger,messages[locale].copy,messages[locale].copy_success),temporarilyChangeIcon(a.trigger)}),a.on('error',a=>{temporarilyChangeTooltip(a.trigger,messages[locale].copy,messages[locale].copy_failure)})};runWhenDOMLoaded(addCopyButtonToCodeCells)