name: spell-checker

on:
  workflow_dispatch:

  workflow_run:
    workflows: [auto-release]
    types:
      - completed

jobs:
  linkchecker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install cspell
        run: npm install -g cspell

      - name: Spell Check
        run: cspell lint --fail-fast .
        shell: dash -e {0}
